### ISSUE TITLE
ftp server down?

### ISSUE THREAD

**Issue by junghans** [HDFGroup/build_hdf5#7]
Try to download hdf5 sources as describe here:
https://support.hdfgroup.org/HDF5/release/obtainsrc518.html#source
getting:
```
Forbidden

You don't have permission to access /ftp/HDF5/releases/ on this server.
Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```
url was: https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.19.tar

Also see spack/spack#6263

**Comment by cyrush** [comment]
several links on the site aren't working, however there are some new obfuscated links that do work.
You can find them on what appears to be the new hdf5 website:  https://www.hdfgroup.org/downloads/hdf5/source-code/#src

That said, obfuscated links will make things very difficult for packages managers like spack.
Hopefully we can get stable URLs for the releases.

**Comment by junghans** [comment]
How about using Gentoo's distfile mirror:
http://distfiles.gentoo.org/distfiles/hdf5-1.8.18.tar.bz2 ?

**Comment by tgamblin** [comment]
does it have current enough versions?

**Comment by junghans** [comment]
Not really, but ANL has http://ftp.mcs.anl.gov/pub/pdetools/externalpackages/

**Comment by tgamblin** [comment]
This is fixed now; HDF5 IT had a permissions error on the FTP server.
